apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
   app: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
        resources: {}
      restartPolicy: Always
