apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  labels:
    type: local
    vol : db-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /tmp/data

